# Generated by Django 4.2.7 on 2023-12-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="RefView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("main", "Main Ref"),
                            ("second", "Second Ref"),
                            ("right", "Goal right"),
                            ("left", "Goal left"),
                        ],
                        max_length=30,
                    ),
                ),
                ("json_record", models.JSONField()),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="juggrefview.game",
                    ),
                ),
            ],
        ),
    ]
